spring.application.name=okpi-discovery-server
server.port=${SERVER_PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:admin12}
